### ISSUE TITLE
Exception during ng serve

### ISSUE THREAD

**Issue by yfain** [gp187/angular2-d3v4-graph#1]
Ran npm install and the ng serve. Got this:

annot find module 'enhanced-resolve/lib/getInnerRequest'
Error: Cannot find module 'enhanced-resolve/lib/getInnerRequest'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/yfain11/Downloads/angular2-d3v4-graph-master/node_modules/@ngtools/webpack/src/paths-plugin.js:6:23)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/yfain11/Downloads/angular2-d3v4-graph-master/node_modules/@ngtools/webpack/src/plugin.js:14:22)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/yfain11/Downloads/angular2-d3v4-graph-master/node_modules/@ngtools/webpack/src/index.js:6:10)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/yfain11/Downloads/angular2-d3v4-graph-master/node_modules/angu

**Comment by cschroeter** [comment]
```
npm install enhanced-resolve

**Comment by gp187** [comment]
Does it work? Never had this problem

**Comment by yfain** [comment]
I've been using yarn instead of npm. I guess, it's the yarn's issue.
